name: Deploy HTML to AWS Lightsail

on:
  push:
    branches:
      - main  # Change this if you use a different branch for deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.AWS_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

        # Validate AWS_HOST secret
        if [[ -z "${{ secrets.AWS_HOST }}" ]]; then
          echo "Error: AWS_HOST is not set!" >&2
          exit 1
        fi

        # Add AWS Server to known hosts to avoid confirmation prompts
        ssh-keyscan -H "${{ secrets.AWS_HOST }}" >> ~/.ssh/known_hosts

    - name: Deploy Files to AWS (aaPanel)
      run: |
        scp -r ./your-html-folder/* root@${{ secrets.AWS_HOST }}:/www/wwwroot/yourdomain.com

    - name: Restart Web Server (Apache or Nginx)
      run: |
        ssh root@${{ secrets.AWS_HOST }} "sudo systemctl restart apache2 || sudo systemctl restart nginx"
